import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="border-2 p-6 flex justify-evenly	">
          <Link href="/" className="bg-green-500 p-4">
            Home
          </Link>
          <Link href="/static" className="bg-green-500 p-4">
            Static
          </Link>
          <Link href="/dynamic" className="bg-green-500 p-4">
            Dynamic
          </Link>
        </nav>
        <div className=" container text-center mt-8 	">{children}</div>
      </body>
    </html>
  );
}
